// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "NÃO PROCEDE", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaCriarCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaCriarCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{ModeloSimples.Infrastructure.Shared.DTO.PessoaModel}}")]
[assembly: SuppressMessage("Usage", "CA2253:Named placeholders should not be numeric values", Justification = "NÃO PROCEDE", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaCriarCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaCriarCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{ModeloSimples.Infrastructure.Shared.DTO.PessoaModel}}")]
[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "NÃO PROCEDE", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaEditarCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaEditarCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{ModeloSimples.Infrastructure.Shared.DTO.PessoaModel}}")]
[assembly: SuppressMessage("Usage", "CA2253:Named placeholders should not be numeric values", Justification = "NÃO PROCEDE", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaEditarCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaEditarCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{ModeloSimples.Infrastructure.Shared.DTO.PessoaModel}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.EventBus.Consumers.PessoaCriadaEventConsumer.Consume(MassTransit.ConsumeContext{ModeloSimples.Domain.Events.PessoaCriadaEvent})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Queries.PessoaObterCommandQueryHandler.Handle(ModeloSimples.Application.Queries.PessoaObterCommandQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoConsulta{ModeloSimples.Infrastructure.Shared.DTO.PessoaModel}}")]
[assembly: SuppressMessage("Usage", "CA2253:Named placeholders should not be numeric values", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Queries.PessoaObterCommandQueryHandler.Handle(ModeloSimples.Application.Queries.PessoaObterCommandQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoConsulta{ModeloSimples.Infrastructure.Shared.DTO.PessoaModel}}")]
[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaRemoverCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaRemoverCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{MediatR.Unit}}")]
[assembly: SuppressMessage("Usage", "CA2253:Named placeholders should not be numeric values", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaRemoverCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaRemoverCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{MediatR.Unit}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.EventBus.Consumers.PessoaDesbloqueadaEventConsumer.Consume(MassTransit.ConsumeContext{ModeloSimples.Domain.Events.PessoaDesbloqueadaEvent})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.EventBus.Consumers.PessoaBloqueadaEventConsumer.Consume(MassTransit.ConsumeContext{ModeloSimples.Domain.Events.PessoaBloqueadaEvent})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2253:Named placeholders should not be numeric values", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaDesbloquearCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaDesbloquearCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{System.Boolean}}")]
[assembly: SuppressMessage("Usage", "CA2253:Named placeholders should not be numeric values", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaBloquearCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaBloquearCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{System.Boolean}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaEditarCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaEditarCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{ModeloSimples.Infrastructure.Shared.DTO.PessoaModel}}")]
[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaRemoverCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaRemoverCommand)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaRemoverCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaRemoverCommand)")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaRemoverCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaRemoverCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{MediatR.Unit}}")]
[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaEditarCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaEditarCommand)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaEditarCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaEditarCommand)")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaBloquearCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaBloquearCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{System.Boolean}}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaCriarCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaCriarCommand)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaBloquearCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaBloquearCommand)")]
[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaBloquearCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaBloquearCommand)")]
[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaCriarCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaCriarCommand)")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaDesbloquearCommandHandler.Handle(ModeloSimples.Application.Commands.PessoaDesbloquearCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ModeloSimples.Infrastructure.Shared.Common.ResultadoOperacao{System.Boolean}}")]
[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaDesbloquearCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaDesbloquearCommand)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ModeloSimples.Application.Commands.PessoaDesbloquearCommandHandler.Validar(ModeloSimples.Application.Commands.PessoaDesbloquearCommand)")]
